# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _gograph
else:
    import _gograph

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


VALUE_NULL = _gograph.VALUE_NULL
VALUE_BOOL = _gograph.VALUE_BOOL
VALUE_INT = _gograph.VALUE_INT
VALUE_FLOAT = _gograph.VALUE_FLOAT
VALUE_STRING = _gograph.VALUE_STRING
VALUE_LIST = _gograph.VALUE_LIST
VALUE_MAP = _gograph.VALUE_MAP
class Value(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    type = property(_gograph.Value_type_get, _gograph.Value_type_set)
    data = property(_gograph.Value_data_get)

    def __init__(self):
        _gograph.Value_swiginit(self, _gograph.new_Value())
    __swig_destroy__ = _gograph.delete_Value

# Register Value in _gograph:
_gograph.Value_swigregister(Value)
class Value_data(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bool_val = property(_gograph.Value_data_bool_val_get, _gograph.Value_data_bool_val_set)
    int_val = property(_gograph.Value_data_int_val_get, _gograph.Value_data_int_val_set)
    float_val = property(_gograph.Value_data_float_val_get, _gograph.Value_data_float_val_set)
    string_val = property(_gograph.Value_data_string_val_get, _gograph.Value_data_string_val_set)
    list_val = property(_gograph.Value_data_list_val_get, _gograph.Value_data_list_val_set)
    map_val = property(_gograph.Value_data_map_val_get, _gograph.Value_data_map_val_set)

    def __init__(self):
        _gograph.Value_data_swiginit(self, _gograph.new_Value_data())
    __swig_destroy__ = _gograph.delete_Value_data

# Register Value_data in _gograph:
_gograph.Value_data_swigregister(Value_data)
class Node(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id = property(_gograph.Node_id_get, _gograph.Node_id_set)
    label = property(_gograph.Node_label_get, _gograph.Node_label_set)
    properties = property(_gograph.Node_properties_get, _gograph.Node_properties_set)
    property_count = property(_gograph.Node_property_count_get, _gograph.Node_property_count_set)

    def __init__(self):
        _gograph.Node_swiginit(self, _gograph.new_Node())
    __swig_destroy__ = _gograph.delete_Node

# Register Node in _gograph:
_gograph.Node_swigregister(Node)
class Relationship(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id = property(_gograph.Relationship_id_get, _gograph.Relationship_id_set)
    type = property(_gograph.Relationship_type_get, _gograph.Relationship_type_set)
    start_node_id = property(_gograph.Relationship_start_node_id_get, _gograph.Relationship_start_node_id_set)
    end_node_id = property(_gograph.Relationship_end_node_id_get, _gograph.Relationship_end_node_id_set)
    properties = property(_gograph.Relationship_properties_get, _gograph.Relationship_properties_set)
    property_count = property(_gograph.Relationship_property_count_get, _gograph.Relationship_property_count_set)

    def __init__(self):
        _gograph.Relationship_swiginit(self, _gograph.new_Relationship())
    __swig_destroy__ = _gograph.delete_Relationship

# Register Relationship in _gograph:
_gograph.Relationship_swigregister(Relationship)
class Path(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    nodes = property(_gograph.Path_nodes_get, _gograph.Path_nodes_set)
    node_count = property(_gograph.Path_node_count_get, _gograph.Path_node_count_set)
    relationships = property(_gograph.Path_relationships_get, _gograph.Path_relationships_set)
    relationship_count = property(_gograph.Path_relationship_count_get, _gograph.Path_relationship_count_set)

    def __init__(self):
        _gograph.Path_swiginit(self, _gograph.new_Path())
    __swig_destroy__ = _gograph.delete_Path

# Register Path in _gograph:
_gograph.Path_swigregister(Path)
class QueryResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    columns = property(_gograph.QueryResult_columns_get, _gograph.QueryResult_columns_set)
    column_count = property(_gograph.QueryResult_column_count_get, _gograph.QueryResult_column_count_set)
    rows = property(_gograph.QueryResult_rows_get, _gograph.QueryResult_rows_set)
    row_count = property(_gograph.QueryResult_row_count_get, _gograph.QueryResult_row_count_set)

    def __init__(self):
        _gograph.QueryResult_swiginit(self, _gograph.new_QueryResult())
    __swig_destroy__ = _gograph.delete_QueryResult

# Register QueryResult in _gograph:
_gograph.QueryResult_swigregister(QueryResult)
class ErrorInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    code = property(_gograph.ErrorInfo_code_get, _gograph.ErrorInfo_code_set)
    message = property(_gograph.ErrorInfo_message_get, _gograph.ErrorInfo_message_set)

    def __init__(self):
        _gograph.ErrorInfo_swiginit(self, _gograph.new_ErrorInfo())
    __swig_destroy__ = _gograph.delete_ErrorInfo

# Register ErrorInfo in _gograph:
_gograph.ErrorInfo_swigregister(ErrorInfo)
GOGRAPH_OK = _gograph.GOGRAPH_OK
GOGRAPH_ERROR_GENERAL = _gograph.GOGRAPH_ERROR_GENERAL
GOGRAPH_ERROR_INVALID_PARAM = _gograph.GOGRAPH_ERROR_INVALID_PARAM
GOGRAPH_ERROR_NOT_FOUND = _gograph.GOGRAPH_ERROR_NOT_FOUND
GOGRAPH_ERROR_ALREADY_EXISTS = _gograph.GOGRAPH_ERROR_ALREADY_EXISTS
GOGRAPH_ERROR_PARSE_FAILURE = _gograph.GOGRAPH_ERROR_PARSE_FAILURE
GOGRAPH_ERROR_EXEC_FAILURE = _gograph.GOGRAPH_ERROR_EXEC_FAILURE
GOGRAPH_ERROR_STORAGE_FAILURE = _gograph.GOGRAPH_ERROR_STORAGE_FAILURE
GOGRAPH_ERROR_MEMORY_ALLOC = _gograph.GOGRAPH_ERROR_MEMORY_ALLOC
GOGRAPH_ERROR_TX_CONFLICT = _gograph.GOGRAPH_ERROR_TX_CONFLICT

def database_new(db_path, error):
    return _gograph.database_new(db_path, error)

def database_open(db_path, error):
    return _gograph.database_open(db_path, error)

def database_close(handle):
    return _gograph.database_close(handle)

def database_free(handle):
    return _gograph.database_free(handle)

def transaction_begin(db_handle, read_only, error):
    return _gograph.transaction_begin(db_handle, read_only, error)

def transaction_commit(tx_handle, error):
    return _gograph.transaction_commit(tx_handle, error)

def transaction_rollback(tx_handle):
    return _gograph.transaction_rollback(tx_handle)

def transaction_free(tx_handle):
    return _gograph.transaction_free(tx_handle)

def cypher_execute(tx_handle, query, params, result, error):
    return _gograph.cypher_execute(tx_handle, query, params, result, error)

def node_create(tx_handle, label, properties, node_id, error):
    return _gograph.node_create(tx_handle, label, properties, node_id, error)

def node_get(tx_handle, node_id, node, error):
    return _gograph.node_get(tx_handle, node_id, node, error)

def node_delete(tx_handle, node_id, error):
    return _gograph.node_delete(tx_handle, node_id, error)

def relationship_create(tx_handle, rel_type, start_node_id, end_node_id, properties, rel_id, error):
    return _gograph.relationship_create(tx_handle, rel_type, start_node_id, end_node_id, properties, rel_id, error)

def relationship_get(tx_handle, rel_id, rel, error):
    return _gograph.relationship_get(tx_handle, rel_id, rel, error)

def query_result_free(result):
    return _gograph.query_result_free(result)

def node_free(node):
    return _gograph.node_free(node)

def relationship_free(rel):
    return _gograph.relationship_free(rel)

def path_free(path):
    return _gograph.path_free(path)

def value_free(value):
    return _gograph.value_free(value)

def error_free(error):
    return _gograph.error_free(error)

